title: 2020 ERA Workshop
logo: /assets/img/logo.png
description: 2020 Emerging Researchers in Artificial Life Workshop (<a href="http://2020.alife.org/">@ ALife 2020</a>)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
